#!/bin/sh

PID="org.webosinternals.speechd"
SID="org.webosinternals.speechd"
LIB="/media/internal/.widk/usr/lib"

APPS=/media/cryptofs/apps

SERVICES_ID=org.webosinternals.speechd.service
SERVICES_PATH=/media/cryptofs/apps/usr/palm/services/$SERVICES_ID

#if [ -z "$IPKG_OFFLINE_ROOT" ]; then
#	/usr/sbin/rootfs_open -w
#fi

# Stop the service if running
/sbin/stop ${SID} || true
/usr/bin/killall -9 ${SID} || true

# Remove the upstart script
rm -f /var/palm/event.d/${SID}

# --- Install Javascript service ---
# make directories in the rare event they don't exist
[ -d /var/palm/ls2/services/prv ] || /bin/mkdir -p /var/palm/ls2/services/prv
[ -d /var/palm/ls2/services/pub ] || /bin/mkdir -p /var/palm/ls2/services/pub

/usr/bin/ls-control scan-services || true

# copy dbus service file
/bin/cp -f $SERVICES_PATH/dbus /var/palm/ls2/services/prv/$SERVICES_ID.service
/bin/cp -f $SERVICES_PATH/dbus /var/palm/ls2/services/pub/$SERVICES_ID.service

# --- Install upstart service ---
# Install the server executable
mkdir -p /var/usr/sbin /var/usr/lib /var/etc
mv ${APPS}/usr/palm/applications/${PID}/etc/speech-dispatcher/modules/espeak-generic.conf0000644 \
	${APPS}/usr/palm/applications/${PID}/etc/speech-dispatcher/modules/espeak-generic.conf || true
cp -R ${APPS}/usr/palm/applications/${PID}/lib/* /var/usr/lib/
cp -R ${APPS}/usr/palm/applications/${PID}/etc/* /var/etc/
cp ${APPS}/usr/palm/applications/${PID}/bin/speech-dispatcher /var/usr/sbin/${SID}

# Install the upstart script
cp ${APPS}/usr/palm/applications/${PID}/upstart/${SID} /var/palm/event.d/${SID}

# put libspeechd.so.2 where others can find it
[ -d ${LIB} ] || mkdir -p ${LIB}
cp ${APPS}/usr/palm/applications/${PID}/lib/libspeechd.so.2 ${LIB}

# Check the upstart script is installed
[ -f /var/palm/event.d/${SID} ] || exit 1

# Start the service
/sbin/start ${SID}
