#!/bin/sh

SID="org.webosinternals.speechd"
LIB="/media/internal/.widk/usr/lib/libspeechd.so.2"

SERVICES_ID="org.webosinternals.speechd.service"

# --- remove Javascript service ---
# remove dbus service file
/bin/rm -f /var/palm/ls2/services/prv/$SERVICES_ID*
/bin/rm -f /var/palm/ls2/services/pub/$SERVICES_ID*

# Stop the service if running
/sbin/stop ${SID} || true
/usr/bin/killall -9 ${SID} || true

# Remove the server executable
rm -f /var/usr/sbin/${SID}
rm -f /var/usr/lib/libdotconf.so.0
rm -f /var/usr/lib/libspeechd.so.2
rm -f /var/usr/lib/libespeak.so.1
rm -rf /var/usr/lib/speech-dispatcher*
rm -rf /var/etc/speech-dispatcher

# Remove the upstart script
rm -f /var/palm/event.d/${SID}

# Remove the lib
rm -f ${LIB}

